### ISSUE TITLE
Can't run some container options from the command-line

### ISSUE THREAD

**Issue by flawmop** [CardiacModelling/appredict-docker#1]
Previously we used to be able to run the containers from the command line so people could run containers independently, as described in https://ap-nimbus.readthedocs.io/en/latest/running/appredict/index.html . I've tried to follow those instructions on the new versions of the containers but have not been able to in some circumstances due to : 

1. ~Changes in the way the PKPD and CellML files are ingested by the container~.  
    ~I'm not sure how to achieve this now as the previous use of docker volumes doesn't seem to work any more~.  
    Uff! Must have been doing something wrong previously, because I've been testing it again and it does work as documented (apart from the `chmod` -- see next point)!
2. `cardiacmodelling/appredict-no-emulators`'s `ApPredict.sh` has stopped being executable.  
    I think that we need to add a `RUN chmod +x ${dir_appredict}/ApPredict.sh` to the `Dockerfile` after [Line 50](https://github.com/CardiacModelling/appredict-docker/blob/f50118b926b238ac8186cb9d86e350706c23a14a/appredict-no-emulators/Dockerfile#L50).   
    `appredict-with-emulators` isn't affected by this as it has a `RUN chmod +x ${dir_appredict}/*.sh` in the [Dockerfile](https://github.com/CardiacModelling/appredict-docker/blob/f50118b926b238ac8186cb9d86e350706c23a14a/appredict-with-emulators/Dockerfile#L15)

**Comment by MauriceHendrix** [comment]
Does anybody actually run the no-emulators one? I have never tried it personally.

**Comment by flawmop** [comment]
Created https://github.com/CardiacModelling/appredict-docker/tree/cli

**Comment by flawmop** [comment]
https://github.com/CardiacModelling/appredict-docker/pull/2

**Comment by flawmop** [comment]
https://github.com/CardiacModelling/ap-nimbus/pull/66

**Comment by flawmop** [comment]
Resolved by https://github.com/CardiacModelling/appredict-docker/pull/2
